export const blogList = [
  {
    id: 1, 
    title: "Unveiling the Unseen: The Fashion-Tech Revolution", 
    img: "https://res.cloudinary.com/dx6qjxz55/image/upload/v1711201612/blog_wq8c2k.avif",
    alt: "Inside of store photo with clothes on shelves",
    author: "Chat GPT", 
    preview: "Dive into the future with our exclusive coverage of the fashion-tech revolution. Beyond smart fabrics and augmented reality, we unravel the hidden gems propelling the industry into uncharted territories. Get ready to be amazed as we showcase the avant-garde creations reshaping the very fabric of style. Discover the unexpected, embrace the extraordinary, and join us on the front lines of innovation.",
    contentIntro: "Fashion and technology converge in an unprecedented dance, birthing a revolution that transcends the conventional boundaries of style. 'Unveiling the Unseen: The Fashion-Tech Revolution' takes you on an exclusive journey through the technological marvels reshaping the landscape of contemporary fashion.",
    contentMainTop: "In a world where innovation is the heartbeat of progress, the fusion of fashion and technology stands as a testament to the limitless possibilities that lie ahead. Join us as we unravel the intricacies of this groundbreaking synergy, exploring virtual runways, smart fabrics, and avant-garde creations that redefine the very essence of wearable art.",
    contentMain: " In the heart of this revolution lies the transcendence of traditional boundaries. Virtual runways, once confined to physical spaces, now become immersive experiences in the digital realm. Fashion designers leverage virtual reality (VR) and augmented reality (AR) to create environments where every step is a stride into the future. Smart fabrics weave a narrative of innovation, turning garments into dynamic expressions of functionality. Temperature-reactive materials, color-changing fabrics &minus; it's not just clothing; it's a canvas of self-expression responding to the world around it. The spotlight falls on the visionaries leading the charge. Through interviews and exclusive stories, we delve into the minds of designers whose artistic visions entwine seamlessly with technological prowess. Each creation becomes a testament to the harmonious marriage of creativity and innovation.",
    contentMainBottom: "Embark with us into the unknown, where the future of fashion-tech beckons. Explore the latest projects, research, and trends shaping tomorrow's style. 'Unveiling the Unseen' is more than an article; it's an invitation to join us on this exhilarating journey into the future of style.",
    contentOutro: "Find inspiration and witness the unprecedented collaboration between fashion and technology.",
    timestamp: "4 JAN 2024 16:00 CET"
  },
  {
    id: 2, 
    title: "Must-Have Fashion Trends for the Upcoming Season", 
    img: "https://res.cloudinary.com/dx6qjxz55/image/upload/v1711201669/store-2_fj9snw.webp",
    alt: "Inside of store photo with clothes on shelves",
    author: "Chat GPT", 
    preview: "Get ready to revamp your wardrobe with the latest fashion trends for the upcoming season. From bold colors to oversized silhouettes and statement prints, this trend report highlights key styles set to dominate runways and streets alike. Embrace sustainability, cozy textures, and utilitarian details to stay ahead of the curve. Let these fashion-forward trends inspire your style journey and make a statement wherever you go.",
    contentIntro: "As the seasons change, so do the trends in the fashion world. Stay ahead of the curve and refresh your wardrobe with the latest must-have fashion trends for the upcoming season. From statement prints to innovative silhouettes, this trend report highlights the key styles that will dominate runways and streets alike. Whether you're a trendsetter or simply looking to update your look, these fashion-forward trends will inspire your style journey.",
    contentMainTop: "Get ready to inject your wardrobe with a dose of color this season. Bold and vibrant hues are set to make a statement, with shades like electric blue, fuchsia pink, and sunshine yellow leading the pack. Whether you opt for head-to-toe monochrome looks or incorporate pops of color into your outfits with accessories, embrace the power of vibrant shades to brighten up your style.",
    contentMain: "Say goodbye to form-fitting silhouettes and hello to oversized shapes. From voluminous blouses to exaggerated outerwear, oversized pieces will reign supreme this season. Embrace the relaxed and effortless vibe of oversized silhouettes, whether you're layering up for colder weather or channeling casual chic for everyday wear.Make a bold statement with eye-catching prints that demand attention. From animal prints to abstract patterns, statement prints will add a playful and dynamic element to your wardrobe. Whether you're drawn to classic leopard print or experimental geometric designs, incorporate prints into your outfits to add depth and personality to your look.",
    contentMainBottom: "Stay cozy and chic with soft and tactile textures that evoke warmth and comfort. From plush knits to sumptuous velvets, tactile fabrics will add a luxurious touch to your wardrobe this season. Embrace the tactile trend with cozy sweaters, plush coats, and velvety dresses that invite touch and elevate your winter style.",
    contentOutro: "As the fashion landscape evolves, so do the trends that define it. Stay ahead of the curve and elevate your style with these must-have fashion trends for the upcoming season. From bold colors and oversized silhouettes to statement prints and sustainable fashion, embrace the latest trends to express your individuality and creativity. Let these fashion-forward trends inspire your wardrobe refresh and make a stylish statement wherever you go.",
    timestamp: "02 MAR 2024 12:00 CET"
  },
  {
    id: 3, 
    title: "Influential Style Icons Throughout History", 
    img: "https://res.cloudinary.com/dx6qjxz55/image/upload/v1711201669/store-1_fq5kwv.webp",
    alt: "Inside of store photo with clothes on shelves",
    author: "Chat GPT", 
    preview: "From the groundbreaking innovations of Coco Chanel to the timeless elegance of Audrey Hepburn and the trailblazing spirit of Rihanna, these influential figures have left an indelible mark on the world of fashion. Delve into the stories of Princess Diana's effortless charm and David Bowie's avant-garde experimentation, discovering how their unique personas continue to inspire generations.",
    contentIntro: "Fashion icons have long captivated our imagination, setting trends and inspiring generations with their distinctive style and charisma. From timeless elegance to avant-garde experimentation, these influential figures have left an indelible mark on the world of fashion, shaping the way we dress and perceive style. In this article, we embark on a journey through history to explore the evolution of fashion icons and celebrate their enduring legacy.",
    contentMainTop: "Coco Chanel (1883-1971): Trailblazing designer Coco Chanel revolutionized women's fashion in the early 20th century with her modern and liberated approach to dressing. From the iconic little black dress to the timeless Chanel suit, her designs epitomized elegance, simplicity, and sophistication. Chanel's penchant for menswear-inspired silhouettes, monochromatic palettes, and luxurious fabrics continues to influence fashion today, making her a timeless style icon.",
    contentMain: "Audrey Hepburn (1929-1993): Actress and humanitarian Audrey Hepburn captivated audiences both on and off the screen with her impeccable style and graceful demeanor. Known for her iconic role in 'Breakfast at Tiffany's,' Hepburn epitomized chic sophistication with her signature black dress, oversized sunglasses, and elegant updos. Her minimalist yet impactful approach to fashion continues to inspire designers and fashion enthusiasts worldwide, solidifying her status as a timeless fashion icon. Diana, Princess of Wales (1961-1997):Princess Diana captured the hearts of the world with her effortless charm, compassion, and impeccable sense of style. From glamorous evening gowns to casual yet chic ensembles, she embraced fashion as a powerful form of self-expression. Princess Diana's iconic looks, including the 'revenge dress' and the 'Elvis dress,' remain etched in fashion history, influencing designers and fashionistas alike with their timeless elegance and sophistication.David Bowie (1947-2016): Musician and style chameleon David Bowie challenged conventions and redefined masculinity with his groundbreaking approach to fashion. From glittering bodysuits to bold makeup and extravagant costumes, Bowie's ever-evolving persona and avant-garde aesthetic pushed the boundaries of gender and identity in fashion. His fearless experimentation and eclectic style continue to inspire artists, designers, and fashion rebels around the world.",
    contentMainBottom: "Rihanna: Entrepreneur, singer, and fashion icon Rihanna has captivated the fashion world with her fearless approach to style and trendsetting prowess. From daring red carpet looks to effortlessly cool streetwear ensembles, Rihanna's eclectic and boundary-pushing style has made her a force to be reckoned with in the fashion industry. With her inclusive lingerie brand Savage x Fenty and groundbreaking collaborations with luxury fashion houses, Rihanna continues to challenge norms and redefine beauty and fashion standards for a new generation of style icons.",
    contentOutro: "From Coco Chanel's timeless elegance to David Bowie's avant-garde experimentation and Rihanna's fearless individuality, fashion icons throughout history have shaped the way we dress, express ourselves, and perceive style. Their influence transcends time and continues to inspire creativity, innovation, and self-expression in the ever-evolving world of fashion. As we celebrate the evolution of fashion icons, let us embrace their legacy and draw inspiration from their fearless spirit and distinctive style.",
    timestamp: "02 MAR 2024 12:00 CET"
  }
]